import { render, screen, fireEvent } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import SummaryForm from "../../src/components/SummaryForm";

describe("SumaryForm", () => {
  test("confirm order initial state", () => {
    render(<SummaryForm />);

    const buttonElm = screen.getByRole("button", { name: /confirm order/i });
    const checkboxElm = screen.getByRole("checkbox", {
      name: /terms and conditions/i,
    });

    // initial state: button enabled, checkbox unchecked
    expect(buttonElm).toBeDisabled();
    expect(checkboxElm).not.toBeChecked();
  });
  test("checkbox enables button on first click and disables on second click", () => {
    render(<SummaryForm />);
    const buttonElm = screen.getByRole("button", { name: /confirm order/i });
    const checkboxElm = screen.getByRole("checkbox", {
      name: /terms and conditions/i,
    });

    // check the checkbox → button should be disabled
    fireEvent.click(checkboxElm);
    expect(buttonElm).toBeEnabled();

    // uncheck the checkbox → button should be enabled again
    fireEvent.click(checkboxElm);
    expect(buttonElm).toBeDisabled();
  });
  test("popover initialy absent and responds on hover", async () => {
    /* this test generated by Claude AI */

    const user = userEvent.setup();
    render(<SummaryForm />);

    // 1. Popover text should not be in the DOM initially
    const nullPopover = screen.queryByText(
      /no ice cream will actually be delivered/i,
    );
    expect(nullPopover).not.toBeInTheDocument();

    // 2. Hover over the "Terms and Conditions" trigger span
    const termsSpan = screen.getByText(/terms and conditions/i);
    await user.hover(termsSpan);

    // 3. Popover text should now be in the DOM
    const popover = screen.getByText(
      /no ice cream will actually be delivered/i,
    );
    expect(popover).toBeInTheDocument();

    // 4. Move mouse away
    await user.unhover(termsSpan);

    // 5. Popover text should be gone from the DOM again
    expect(
      screen.queryByText(/no ice cream will actually be delivered/i),
    ).not.toBeInTheDocument();
  });
});
